name = "Crystalline"
uuid = "ae5e2be0-a263-11e9-351e-f94dad1eb351"
authors = ["Thomas Christensen <tchr@mit.edu>"]
version = "0.4.9"

[deps]
Bravais = "ada6cbde-b013-4edf-aa94-f6abe8bd6e6b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshing = "e6723b4c-ebff-59f1-b4b7-d97aa5274f73"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Bravais = "0.1"
Combinatorics = "1.0"
DocStringExtensions = "0.8"
JLD2 = "0.2.4, 0.4"
Meshing = "0.5"
PrettyTables = "0.12, 1.0, 1.1"
Reexport = "1.0, 1.1, 1.2"
Requires = "1.0, 1.1"
StaticArrays = "1.2.8"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
